### PR TITLE
Relax negative scales conditions in Quant Dialect

### PR DESCRIPTION
**Pull request by ZoranZomborat**
## Summary

 Relax negative scales conditions; such to support negative scales natively in NPU HW.

## JIRA ticket

* E-138352

## Related PR in NPU Compiler and/or OpenVINO repository with sub-module update

* PR-xxx

* E-xxxxx

### CODE REVIEW

**Comment by ZoranZomborat** [comment]
Need to test updated LIT tests locally

**Comment by ZoranZomborat** [comment]
@hrotuna @andrey-golubev @nikita-kud @AndreiFilipIntel @sartil  please review

**Review by AndreiFilipIntel — APPROVED** [review]

**Review by hrotuna — APPROVED** [review]

**Comment by ZoranZomborat** [comment]
Locally mlir-check is also passing

**Comment by ZoranZomborat** [comment]
@nikita-kud  I see you've added a task to track the upstream of these changes https://jira.devtools.intel.com/browse/EISW-141776 thanks!
Personally I don't think it'll be a hard task to upstream them. Can we merge this PR as it is?

**Review by sartil — APPROVED** [review]
LGTM!

**Comment by nikita-kud** [comment]
Can we get green CI [here](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/13158) first please?

**Comment by ZoranZomborat** [comment]
> Can we get green CI [here](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/13158) first please?

Sure, I'll dig more, hopefully there's not much left to fix

**Comment by sartil** [comment]
> > Can we get green CI [here](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/13158) first please?
> 
> Sure, I'll dig more, hopefully there's not much left to fix

It was happening randomly as well in my PR: the jobs don't seem to fail, they get skipped or cancelled for some reason

**Comment by ZoranZomborat** [comment]
@nikita-kud  @hrotuna  there is only one ISV network failing on the compiler PR, otherwise all if green, can we merge this dependency ?

**Comment by hrotuna** [comment]
No objections from my side.

**Pull request merged**
